# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/carte.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(581, 380)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/img/assets/experience_pro.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.capture_btn = QtWidgets.QPushButton(Dialog)
        self.capture_btn.setGeometry(QtCore.QRect(240, 342, 111, 31))
        self.capture_btn.setStyleSheet(
            "QPushButton{\n"
            "    color:#777fff;\n"
            "    border:1px solid #777fff;\n"
            "    background-color: white;\n"
            "    border-radius:15px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    color: rgb(255, 255, 255);\n"
            "    background-color:#777fff;\n"
            "}"
        )
        self.capture_btn.setObjectName("capture_btn")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(40, 30, 501, 301))
        self.frame.setStyleSheet(
            "border:1px solid rgb(193, 193, 193);\n"
            "border-radius:20px;\n"
            'font: 11pt "Roboto";\n'
            "background-color:rgb(249, 249, 249);\n"
            ""
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.photo = QtWidgets.QLabel(self.frame)
        self.photo.setGeometry(QtCore.QRect(20, 80, 111, 131))
        self.photo.setStyleSheet(
            "border:1px solid rgb(193, 193, 193);\n"
            "padding:1px;\n"
            "border-radius:1px;"
        )
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap(":/img/assets/photo.png"))
        self.photo.setScaledContents(True)
        self.photo.setAlignment(QtCore.Qt.AlignCenter)
        self.photo.setObjectName("photo")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 281, 31))
        self.label_2.setStyleSheet(
            "border:none;\n" "color:rgb(0, 170, 0);\n" 'font: 14pt "Roboto";'
        )
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(180, 40, 131, 16))
        self.label_3.setStyleSheet(
            'font: 57 7pt "Roboto Medium";\n' "color: rgb(255, 0, 0);\n" "border:none;"
        )
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(150, 100, 171, 13))
        self.label_4.setStyleSheet(
            "border:none;\n" 'font: 8pt "Roboto";\n' "font-style:italic;"
        )
        self.label_4.setObjectName("label_4")
        self.nom_field = QtWidgets.QLineEdit(self.frame)
        self.nom_field.setGeometry(QtCore.QRect(150, 81, 221, 20))
        self.nom_field.setStyleSheet("border:none;\n" 'font: 57 13pt "Roboto Medium";')
        self.nom_field.setMaxLength(23)
        self.nom_field.setReadOnly(True)
        self.nom_field.setObjectName("nom_field")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(150, 226, 151, 13))
        self.label_5.setStyleSheet(
            "border:none;\n" 'font: 8pt "Roboto";\n' "font-style:italic;"
        )
        self.label_5.setObjectName("label_5")
        self.nationalite_field = QtWidgets.QLineEdit(self.frame)
        self.nationalite_field.setGeometry(QtCore.QRect(320, 205, 141, 20))
        self.nationalite_field.setStyleSheet(
            "border:none;\n" 'font: 57 13pt "Roboto Medium";'
        )
        self.nationalite_field.setMaxLength(13)
        self.nationalite_field.setReadOnly(True)
        self.nationalite_field.setObjectName("nationalite_field")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(150, 186, 111, 14))
        self.label_6.setStyleSheet(
            "border:none;\n" 'font: 8pt "Roboto";\n' "font-style:italic;"
        )
        self.label_6.setObjectName("label_6")
        self.date_field = QtWidgets.QLineEdit(self.frame)
        self.date_field.setGeometry(QtCore.QRect(150, 167, 111, 20))
        self.date_field.setStyleSheet("border:none;\n" 'font: 57 13pt "Roboto Medium";')
        self.date_field.setReadOnly(True)
        self.date_field.setObjectName("date_field")
        self.sexe_field = QtWidgets.QLineEdit(self.frame)
        self.sexe_field.setGeometry(QtCore.QRect(273, 167, 21, 20))
        self.sexe_field.setStyleSheet("border:none;\n" 'font: 57 13pt "Roboto Medium";')
        self.sexe_field.setAlignment(QtCore.Qt.AlignCenter)
        self.sexe_field.setReadOnly(True)
        self.sexe_field.setObjectName("sexe_field")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(270, 186, 31, 16))
        self.label_7.setStyleSheet(
            "border:none;\n" 'font: 8pt "Roboto";\n' "font-style:italic;"
        )
        self.label_7.setObjectName("label_7")
        self.lieu_field = QtWidgets.QLineEdit(self.frame)
        self.lieu_field.setGeometry(QtCore.QRect(320, 167, 151, 20))
        self.lieu_field.setStyleSheet("border:none;\n" 'font: 57 13pt "Roboto Medium";')
        self.lieu_field.setMaxLength(18)
        self.lieu_field.setReadOnly(True)
        self.lieu_field.setObjectName("lieu_field")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(320, 186, 101, 16))
        self.label_8.setStyleSheet(
            "border:none;\n" 'font: 8pt "Roboto";\n' "font-style:italic;"
        )
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(320, 226, 111, 16))
        self.label_11.setStyleSheet(
            "border:none;\n" 'font: 8pt "Roboto";\n' "font-style:italic;"
        )
        self.label_11.setObjectName("label_11")
        self.domicile_field = QtWidgets.QLineEdit(self.frame)
        self.domicile_field.setGeometry(QtCore.QRect(150, 205, 151, 20))
        self.domicile_field.setStyleSheet(
            "border:none;\n" 'font: 57 13pt "Roboto Medium";'
        )
        self.domicile_field.setMaxLength(14)
        self.domicile_field.setReadOnly(True)
        self.domicile_field.setObjectName("domicile_field")
        self.prenom_field = QtWidgets.QLineEdit(self.frame)
        self.prenom_field.setGeometry(QtCore.QRect(150, 115, 261, 20))
        self.prenom_field.setStyleSheet(
            "border:none;\n" 'font: 57 13pt "Roboto Medium";'
        )
        self.prenom_field.setMaxLength(24)
        self.prenom_field.setReadOnly(True)
        self.prenom_field.setObjectName("prenom_field")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(150, 134, 111, 13))
        self.label_9.setStyleSheet(
            "border:none;\n" 'font: 8pt "Roboto";\n' "font-style:italic;"
        )
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(410, 10, 71, 71))
        self.label_10.setStatusTip("")
        self.label_10.setStyleSheet("border:none;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/img/assets/armoirie2.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setWordWrap(False)
        self.label_10.setOpenExternalLinks(False)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(34, 217, 14, 16))
        self.label_12.setStyleSheet(
            "border:none;\n" 'font: 8pt "Roboto";\n' "font-style:italic;"
        )
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(54, 217, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet('font: 8pt "Roboto";\n' "border:none;")
        self.label_13.setObjectName("label_13")
        self.id_field = QtWidgets.QLineEdit(self.frame)
        self.id_field.setGeometry(QtCore.QRect(105, 217, 15, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.id_field.setFont(font)
        self.id_field.setWhatsThis("")
        self.id_field.setStyleSheet('font: 8pt "Roboto";\n' "border:none;")
        self.id_field.setInputMask("")
        self.id_field.setReadOnly(True)
        self.id_field.setObjectName("id_field")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(320, 280, 141, 13))
        self.label_14.setStyleSheet(
            "border:none;\n" 'font: 8pt "Roboto";\n' "font-style:italic;"
        )
        self.label_14.setObjectName("label_14")
        self.pere_field = QtWidgets.QLineEdit(self.frame)
        self.pere_field.setGeometry(QtCore.QRect(150, 260, 161, 20))
        self.pere_field.setStyleSheet("border:none;\n" 'font: 57 13pt "Roboto Medium";')
        self.pere_field.setMaxLength(16)
        self.pere_field.setReadOnly(True)
        self.pere_field.setObjectName("pere_field")
        self.mere_field = QtWidgets.QLineEdit(self.frame)
        self.mere_field.setGeometry(QtCore.QRect(320, 260, 161, 20))
        self.mere_field.setStyleSheet("border:none;\n" 'font: 57 13pt "Roboto Medium";')
        self.mere_field.setMaxLength(16)
        self.mere_field.setCursorPosition(4)
        self.mere_field.setReadOnly(True)
        self.mere_field.setObjectName("mere_field")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(150, 280, 151, 13))
        self.label_15.setStyleSheet(
            "border:none;\n" 'font: 8pt "Roboto";\n' "font-style:italic;"
        )
        self.label_15.setObjectName("label_15")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 236, 41, 41))
        self.label.setStyleSheet("border:none;")
        self.label.setText("")
        self.label.setPixmap(
            QtGui.QPixmap(":/img/assets/cote-divoire-1758956_960_720.png")
        )
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Carte d'identité"))
        self.capture_btn.setText(_translate("Dialog", "GENERER"))
        self.label_2.setText(_translate("Dialog", "REPUBLIQUE DE CÔTE D'IVOIRE"))
        self.label_3.setText(_translate("Dialog", "CARTE NATIONNAL D'IDENTITE"))
        self.label_4.setText(_translate("Dialog", "Nom"))
        self.nom_field.setText(_translate("Dialog", "ffff5855542145536655255"))
        self.label_5.setText(_translate("Dialog", "Domicile"))
        self.nationalite_field.setText(_translate("Dialog", "ddd5555555555"))
        self.label_6.setText(_translate("Dialog", "Date de Naissance"))
        self.date_field.setText(_translate("Dialog", "ddd5862489"))
        self.sexe_field.setText(_translate("Dialog", "h"))
        self.label_7.setText(_translate("Dialog", "Sexe"))
        self.lieu_field.setText(_translate("Dialog", "addddrrrrrreereefh"))
        self.label_8.setText(_translate("Dialog", "Lieu de Naissance"))
        self.label_11.setText(_translate("Dialog", "Nationalité"))
        self.domicile_field.setText(_translate("Dialog", "58855555222222"))
        self.prenom_field.setText(_translate("Dialog", "ffff55555555555555555555"))
        self.label_9.setText(_translate("Dialog", "Prénom(s)"))
        self.label_12.setText(_translate("Dialog", "n°"))
        self.label_13.setText(_translate("Dialog", "CI0008011"))
        self.id_field.setText(_translate("Dialog", "45"))
        self.label_14.setText(_translate("Dialog", "Nom et Prénom de la Mère"))
        self.pere_field.setText(_translate("Dialog", "dddd"))
        self.mere_field.setText(_translate("Dialog", "ttyy"))
        self.label_15.setText(_translate("Dialog", "Nom et Prénom du Père"))


import imageQtDesigner_rc
