# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/formulaire.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1299, 684)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/img/assets/1914868.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(16, 20, 541, 621))
        self.widget.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" 'font: 14pt "Roboto";\n' ""
        )
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 22, 541, 41))
        self.label.setStyleSheet(
            "border-radius:5px;\n"
            "background-color:#777fff;\n"
            "color: rgb(255, 255, 255);\n"
            'font: 57 16pt "Roboto Medium";'
        )
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 98, 81, 16))
        self.label_2.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.label_2.setObjectName("label_2")
        self.nom_field = QtWidgets.QLineEdit(self.widget)
        self.nom_field.setGeometry(QtCore.QRect(110, 92, 261, 30))
        self.nom_field.setStyleSheet(
            "padding-lefl:10px;\n" "border:1px solid #444;\n" "border-radius:5px;"
        )
        self.nom_field.setAlignment(QtCore.Qt.AlignCenter)
        self.nom_field.setObjectName("nom_field")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 144, 81, 16))
        self.label_3.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.label_3.setObjectName("label_3")
        self.prenom_field = QtWidgets.QLineEdit(self.widget)
        self.prenom_field.setGeometry(QtCore.QRect(110, 138, 261, 30))
        self.prenom_field.setStyleSheet(
            "padding-lefl:10px;\n" "border:1px solid #444;\n" "border-radius:5px;"
        )
        self.prenom_field.setAlignment(QtCore.Qt.AlignCenter)
        self.prenom_field.setObjectName("prenom_field")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 204, 131, 16))
        self.label_4.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 248, 121, 16))
        self.label_5.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 331, 81, 16))
        self.label_6.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(40, 434, 181, 16))
        self.label_7.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(20, 374, 85, 16))
        self.label_8.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(40, 500, 201, 16))
        self.label_9.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.label_9.setObjectName("label_9")
        self.photo_btn = QtWidgets.QPushButton(self.widget)
        self.photo_btn.setGeometry(QtCore.QRect(390, 250, 131, 31))
        self.photo_btn.setStyleSheet(
            "QPushButton{\n"
            '    font: 9pt "Roboto";\n'
            "    border-style: solid;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
            "    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
            "    border-width: 1px;\n"
            "    border-radius: 15px;\n"
            "    color: rgb(0,0,0);\n"
            "    padding: 2px;\n"
            "    background-color: rgb(255,255,255);\n"
            "}\n"
            "QPushButton::default{\n"
            "    border-style: solid;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
            "    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
            "    border-width: 1px;\n"
            "    border-radius: 5px;\n"
            "    color: rgb(0,0,0);\n"
            "    padding: 2px;\n"
            "    background-color: rgb(255,255,255);\n"
            "}\n"
            "QPushButton:hover{\n"
            "    border-style: solid;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
            "    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
            "    border-width: 1px;\n"
            "    border-radius: 5px;\n"
            "    color: rgb(0,0,0);\n"
            "    padding: 2px;\n"
            "    background-color: rgb(255,255,255);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border-style: solid;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
            "    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
            "    border-width: 1px;\n"
            "    border-radius: 5px;\n"
            "    color: rgb(0,0,0);\n"
            "    padding: 2px;\n"
            "    background-color: rgb(142,142,142);\n"
            "}\n"
            "QPushButton:disabled{\n"
            "    border-style: solid;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
            "    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
            "    border-width: 1px;\n"
            "    border-radius: 5px;\n"
            "    color: #808086;\n"
            "    padding: 2px;\n"
            "    background-color: rgb(142,142,142);\n"
            "}"
        )
        self.photo_btn.setObjectName("photo_btn")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(20, 290, 61, 16))
        self.label_10.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.label_10.setObjectName("label_10")
        self.photo = QtWidgets.QLabel(self.widget)
        self.photo.setGeometry(QtCore.QRect(390, 91, 131, 151))
        self.photo.setStyleSheet(
            "border:1px solid rgb(198, 198, 198);\n" "padding:1px;\n" ""
        )
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap(":/img/assets/photo.png"))
        self.photo.setScaledContents(True)
        self.photo.setAlignment(QtCore.Qt.AlignCenter)
        self.photo.setObjectName("photo")
        self.date_field = QtWidgets.QDateEdit(self.widget)
        self.date_field.setGeometry(QtCore.QRect(170, 199, 201, 29))
        self.date_field.setStyleSheet(
            "QDateEdit{\n"
            "padding-lefl:10px;\n"
            "border:1px solid #444;\n"
            "border-radius:5px;\n"
            "color: rgb(0, 0, 0);\n"
            "}\n"
            "QDateEdit::drop-down {\n"
            "    image: url(:/img/assets/arrow-down-sign-to-navigate.png);\n"
            "    width:20px;\n"
            "    padding:5px;\n"
            "    subcontrol-position: right top;\n"
            "    subcontrol-origin:padding;\n"
            "    border-left:1px solid #444;\n"
            "    color:black;\n"
            "}"
        )
        self.date_field.setAlignment(QtCore.Qt.AlignCenter)
        self.date_field.setReadOnly(False)
        self.date_field.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.date_field.setSpecialValueText("")
        self.date_field.setCorrectionMode(
            QtWidgets.QAbstractSpinBox.CorrectToPreviousValue
        )
        self.date_field.setKeyboardTracking(True)
        self.date_field.setProperty("showGroupSeparator", False)
        self.date_field.setDateTime(
            QtCore.QDateTime(QtCore.QDate(1921, 1, 1), QtCore.QTime(0, 0, 0))
        )
        self.date_field.setMaximumDate(QtCore.QDate(2221, 12, 31))
        self.date_field.setMinimumDate(QtCore.QDate(1921, 1, 1))
        self.date_field.setCalendarPopup(True)
        self.date_field.setDate(QtCore.QDate(1921, 1, 1))
        self.date_field.setObjectName("date_field")
        self.lieu_field = QtWidgets.QLineEdit(self.widget)
        self.lieu_field.setGeometry(QtCore.QRect(170, 242, 201, 30))
        self.lieu_field.setStyleSheet(
            "padding-lefl:10px;\n" "border:1px solid #444;\n" "border-radius:5px;"
        )
        self.lieu_field.setAlignment(QtCore.Qt.AlignCenter)
        self.lieu_field.setObjectName("lieu_field")
        self.genre_h = QtWidgets.QRadioButton(self.widget)
        self.genre_h.setGeometry(QtCore.QRect(110, 290, 82, 17))
        self.genre_h.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.genre_h.setCheckable(True)
        self.genre_h.setChecked(True)
        self.genre_h.setObjectName("genre_h")
        self.genre_f = QtWidgets.QRadioButton(self.widget)
        self.genre_f.setGeometry(QtCore.QRect(287, 290, 82, 17))
        self.genre_f.setStyleSheet("border:none;\n" 'font: 10pt "Roboto";')
        self.genre_f.setChecked(False)
        self.genre_f.setObjectName("genre_f")
        self.domicile_field = QtWidgets.QLineEdit(self.widget)
        self.domicile_field.setGeometry(QtCore.QRect(110, 325, 261, 30))
        self.domicile_field.setStyleSheet(
            "padding-lefl:10px;\n" "border:1px solid #444;\n" "border-radius:5px;"
        )
        self.domicile_field.setAlignment(QtCore.Qt.AlignCenter)
        self.domicile_field.setObjectName("domicile_field")
        self.nationalite_field = QtWidgets.QLineEdit(self.widget)
        self.nationalite_field.setGeometry(QtCore.QRect(110, 367, 261, 30))
        self.nationalite_field.setStyleSheet(
            "padding-lefl:10px;\n" "border:1px solid #444;\n" "border-radius:5px;"
        )
        self.nationalite_field.setAlignment(QtCore.Qt.AlignCenter)
        self.nationalite_field.setObjectName("nationalite_field")
        self.pere_field = QtWidgets.QLineEdit(self.widget)
        self.pere_field.setGeometry(QtCore.QRect(40, 457, 461, 30))
        self.pere_field.setStyleSheet(
            "padding-lefl:10px;\n" "border:1px solid #444;\n" "border-radius:5px;"
        )
        self.pere_field.setText("")
        self.pere_field.setAlignment(QtCore.Qt.AlignCenter)
        self.pere_field.setDragEnabled(False)
        self.pere_field.setObjectName("pere_field")
        self.mere_field = QtWidgets.QLineEdit(self.widget)
        self.mere_field.setGeometry(QtCore.QRect(40, 520, 461, 30))
        self.mere_field.setStyleSheet(
            "padding-lefl:10px;\n" "border:1px solid #444;\n" "border-radius:5px;"
        )
        self.mere_field.setAlignment(QtCore.Qt.AlignCenter)
        self.mere_field.setObjectName("mere_field")
        self.nettoyer_btn = QtWidgets.QPushButton(self.widget)
        self.nettoyer_btn.setGeometry(QtCore.QRect(30, 570, 151, 40))
        self.nettoyer_btn.setStyleSheet(
            "QPushButton{\n"
            '    font: 57 12pt "Roboto Medium";\n'
            "    border-style: solid;\n"
            "    border-color: rgb(85, 85, 85);\n"
            "    border-width: 1px;\n"
            "    border-radius: 20px;\n"
            "    color: rgb(0,0,0);\n"
            "    padding: 2px;\n"
            "    background-color: rgb(255,255,255);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border:none;\n"
            "    border-radius: 20px;\n"
            "    color: rgb(0,0,0);\n"
            "    padding: 2px;\n"
            "    background-color: rgb(142,142,142);\n"
            "}\n"
            "QPushButton:disabled{\n"
            "    border-style: solid;\n"
            "    border-color: rgb(85, 85, 85);\n"
            "    border-radius: 20px;\n"
            "    color: #808086;\n"
            "    padding: 2px;\n"
            "    background-color: rgb(142,142,142);\n"
            "}"
        )
        self.nettoyer_btn.setObjectName("nettoyer_btn")
        self.envoyer_btn = QtWidgets.QPushButton(self.widget)
        self.envoyer_btn.setGeometry(QtCore.QRect(360, 570, 151, 40))
        self.envoyer_btn.setStyleSheet(
            "QPushButton{\n"
            '    font: 57 12pt "Roboto Medium";\n'
            "    background-color:#777fff;\n"
            "    color:white;\n"
            "    border:none;\n"
            "    border-radius:20px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color:#0069d9;\n"
            "}\n"
            ""
        )
        self.envoyer_btn.setObjectName("envoyer_btn")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(576, 169, 709, 401))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.apercu_btn = QtWidgets.QPushButton(self.centralwidget)
        self.apercu_btn.setGeometry(QtCore.QRect(860, 590, 131, 40))
        self.apercu_btn.setStyleSheet(
            "QPushButton{\n"
            "    color:white;\n"
            "    border:none;\n"
            "    border-radius:18px;\n"
            '    font: 57 12pt "Roboto Medium";\n'
            "    background-color:#777fff;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color:#0069d9;\n"
            "}\n"
            ""
        )
        self.apercu_btn.setObjectName("apercu_btn")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(573, 43, 711, 41))
        self.label_12.setStyleSheet(
            "border-radius:5px;\n"
            "color: rgb(255, 255, 255);\n"
            'font: 57 16pt "Roboto Medium";\n'
            "background-color:#777fff;"
        )
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.modifier_btn = QtWidgets.QPushButton(self.centralwidget)
        self.modifier_btn.setGeometry(QtCore.QRect(620, 590, 131, 40))
        self.modifier_btn.setStyleSheet(
            "QPushButton{\n"
            '    font: 57 12pt "Roboto Medium";\n'
            "    border-style: solid;\n"
            "    border-color: rgb(85, 85, 85);\n"
            "    border-width: 1px;\n"
            "    border-radius: 18px;\n"
            "    color: rgb(0,0,0);\n"
            "    padding: 2px;\n"
            "    background-color: rgb(255,255,255);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border:none;\n"
            "    border-radius: 18px;\n"
            "    color: rgb(0,0,0);\n"
            "    padding: 2px;\n"
            "    background-color: rgb(142,142,142);\n"
            "}\n"
            "QPushButton:disabled{\n"
            "    border-style: solid;\n"
            "    border-color: rgb(85, 85, 85);\n"
            "    border-radius: 18px;\n"
            "    color: #808086;\n"
            "    padding: 2px;\n"
            "    background-color: rgb(142,142,142);\n"
            "}"
        )
        self.modifier_btn.setObjectName("modifier_btn")
        self.supprimer_btn = QtWidgets.QPushButton(self.centralwidget)
        self.supprimer_btn.setGeometry(QtCore.QRect(1100, 590, 131, 40))
        self.supprimer_btn.setStyleSheet(
            "QPushButton{\n"
            '    font: 57 12pt "Roboto Medium";\n'
            "    color:white;\n"
            "    border:none;\n"
            "    border-radius:18px;\n"
            "    background-color:#dc3545;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #c82333;\n"
            "}\n"
            ""
        )
        self.supprimer_btn.setObjectName("supprimer_btn")
        self.recherche_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.recherche_edit.setGeometry(QtCore.QRect(589, 122, 291, 31))
        self.recherche_edit.setStyleSheet(
            "border:1px solid black;\n"
            "border-right-color: none;\n"
            'font: 11pt "Roboto";\n'
            "border-top-left-radius: 12px;\n"
            "border-bottom-left-radius: 14px;\n"
            "padding:5px;"
        )
        self.recherche_edit.setText("")
        self.recherche_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.recherche_edit.setObjectName("recherche_edit")
        self.search_icon = QtWidgets.QLabel(self.centralwidget)
        self.search_icon.setGeometry(QtCore.QRect(877, 122, 31, 31))
        self.search_icon.setStyleSheet(
            "border:1px solid black;\n"
            "border-left-color: none;\n"
            "background-color: rgb(255, 255, 255);\n"
            "border-top-right-radius: 14px;\n"
            "border-bottom-right-radius: 14px;\n"
            "padding: 5px"
        )
        self.search_icon.setText("")
        self.search_icon.setPixmap(QtGui.QPixmap(":/img/assets/search.png"))
        self.search_icon.setScaledContents(True)
        self.search_icon.setObjectName("search_icon")
        self.filtre_field = QtWidgets.QComboBox(self.centralwidget)
        self.filtre_field.setGeometry(QtCore.QRect(990, 122, 151, 31))
        self.filtre_field.setStyleSheet(
            "QComboBox{\n"
            "border:1px solid black;\n"
            'font: 11pt "Roboto";\n'
            "border-radius: 14px;\n"
            "padding:5px;\n"
            "}\n"
            "QComboBox::drop-down {\n"
            "    image: url(:/img/assets/arrow-down-sign-to-navigate.png);\n"
            "    width:20px;\n"
            "    padding:6px;\n"
            "    subcontrol-position: right top;\n"
            "    subcontrol-origin:padding;\n"
            "    border-left:1px solid #444;\n"
            "    color:black;\n"
            "}\n"
            ""
        )
        self.filtre_field.setDuplicatesEnabled(False)
        self.filtre_field.setObjectName("filtre_field")
        self.filtre_field.addItem("")
        self.filtre_field.addItem("")
        self.filtre_field.addItem("")
        self.filtrer_btn = QtWidgets.QPushButton(self.centralwidget)
        self.filtrer_btn.setGeometry(QtCore.QRect(1150, 122, 111, 31))
        self.filtrer_btn.setStyleSheet(
            "QPushButton{\n"
            '    font: 57 10pt "Roboto Medium";\n'
            "    border-style: solid;\n"
            "    border-color: rgb(85, 85, 85);\n"
            "    border-width: 1px;\n"
            "    border-radius: 15px;\n"
            "    color: rgb(0,0,0);\n"
            "    padding: 2px;\n"
            "    background-color: rgb(255,255,255);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border:none;\n"
            "    border-radius: 15px;\n"
            "    color: rgb(0,0,0);\n"
            "    padding: 2px;\n"
            "    background-color: rgb(142,142,142);\n"
            "}\n"
            "QPushButton:disabled{\n"
            "    border-style: solid;\n"
            "    border-color: rgb(85, 85, 85);\n"
            "    border-radius: 15px;\n"
            "    color: #808086;\n"
            "    padding: 2px;\n"
            "    background-color: rgb(142,142,142);\n"
            "}"
        )
        self.filtrer_btn.setObjectName("filtrer_btn")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(556, -10, 16, 671))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1299, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Formulaire d'enrolement"))
        self.label.setText(_translate("MainWindow", "FORMULAIRE D'ENROLEMENT"))
        self.label_2.setText(_translate("MainWindow", "NOM"))
        self.label_3.setText(_translate("MainWindow", "PRENOM(S)"))
        self.label_4.setText(_translate("MainWindow", "DATE DE NAISSANCE"))
        self.label_5.setText(_translate("MainWindow", "LIEU DE NAISSANCE"))
        self.label_6.setText(_translate("MainWindow", "DOMICILE"))
        self.label_7.setText(_translate("MainWindow", "NOM ET PRENOM(S) DU PERE"))
        self.label_8.setText(_translate("MainWindow", "NATIONALITE"))
        self.label_9.setText(_translate("MainWindow", "NOM ET PRENOM(S) DE LA MERE"))
        self.photo_btn.setText(_translate("MainWindow", "CHOISIR PHOTO"))
        self.label_10.setText(_translate("MainWindow", "GENRE"))
        self.genre_h.setText(_translate("MainWindow", "Masculin"))
        self.genre_f.setText(_translate("MainWindow", "Feminin"))
        self.nettoyer_btn.setText(_translate("MainWindow", "NETTOYER"))
        self.envoyer_btn.setText(_translate("MainWindow", "ENVOYER"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nom"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prénom(s)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date de Naisance"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Lieu de Naissance"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Genre"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Domicile"))
        self.apercu_btn.setText(_translate("MainWindow", "APERCU"))
        self.label_12.setText(
            _translate("MainWindow", "LISTE DES PERSONNES ENREGISTREES")
        )
        self.modifier_btn.setText(_translate("MainWindow", "MODIFIER"))
        self.supprimer_btn.setText(_translate("MainWindow", "SUPPRIMER"))
        self.recherche_edit.setPlaceholderText(
            _translate("MainWindow", "nom, prenom ou domicile")
        )
        self.filtre_field.setItemText(0, _translate("MainWindow", "Tout"))
        self.filtre_field.setItemText(1, _translate("MainWindow", "Masculin (M)"))
        self.filtre_field.setItemText(2, _translate("MainWindow", "Feminin (F)"))
        self.filtrer_btn.setText(_translate("MainWindow", "FILTRER"))


import imageQtDesigner_rc
